# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '510dd4ae-6756-4bbe-bea0-4a501fbfc583'
  imageRepository_view: 'viewmicroservice'
  imageRepository_add: 'addmicroservice'
  imageRepository_nginx: 'nginxmicroservice'
  containerRegistry: 'xxdockerimage.azurecr.io'
  dockerfilePath_view: '**/Dockerfile_view_data'
  dockerfilePath_add: '**/Dockerfile_add_data'
  dockerfilePath_nginx: '**/Dockerfile_nginx'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'xxdockerimage1944a094-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: dev
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository_view)
        dockerfile: $(dockerfilePath_view)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository_add)
        dockerfile: $(dockerfilePath_add)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository_nginx)
        dockerfile: $(dockerfilePath_nginx)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: dev
      vmImage: $(vmImageName)
    environment: 'rahulwaynepyappmicroservice.pyapp-microservice'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository_view):$(tag)
                $(containerRegistry)/$(imageRepository_add):$(tag)

