# Use the official Nginx image from Docker Hub
FROM nginx:alpine

# Remove the default nginx index page
RUN rm /usr/share/nginx/html/*
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom index.html into the nginx container
COPY templates/index.html /usr/share/nginx/html
COPY conf/default.conf /etc/nginx/conf.d

# Expose port 80
EXPOSE 80

# Start Nginx and keep it running in the foreground
CMD ["nginx", "-g", "daemon off;"]