apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:latest
        command: ["sh", "-c", "mongosh --host mongodb-service --eval 'use microserviceDB; db.createCollection(\"data\")'"]
      restartPolicy: OnFailure

---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-deployment
  labels:
    app: view-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-microservice
  template:
    metadata:
      labels:
        app: view-microservice
    spec:
      containers:
      - name: view-microservice
        image: xxdockerimage.azurecr.io/rahulwayneview-microservice
        ports:
        - containerPort: 5002

---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
  labels:
    app: add-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-microservice
  template:
    metadata:
      labels:
        app: add-microservice
    spec:
      containers:
      - name: add-microservice
        image: xxdockerimage.azurecr.io/rahulwayneadd-microservice
        ports:
        - containerPort: 5001