---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: view-service
spec:
  selector:
    app: view-microservice
  ports:
    - protocol: TCP
      port: 5002
      #targetPort: 5002
  #type: LoadBalancer
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  selector:
    app: add-microservice
  ports:
    - protocol: TCP
      port: 5001
      #targetPort: 5001
  #type: LoadBalancer
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - port: 80  # The service port
    targetPort: 80  # The container port
  type: LoadBalancer
  #nodePort: 30007  # The port exposed on each node